mcv_app1/mcv_app1/Controllers/DeliverymanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mcv_app1.Models;

namespace mcv_app1.Controllers
{
    public class DeliverymanController : Controller
    {
        private OrderDB db = new OrderDB();

        //
        // GET: /Deliveryman/

        public ActionResult Index()
        {
            return View(db.Deliverymen.ToList());
        }

        //
        // GET: /Deliveryman/Details/5

        public ActionResult Details(int id = 0)
        {
            Deliveryman deliveryman = db.Deliverymen.Find(id);
            if (deliveryman == null)
            {
                return HttpNotFound();
            }
            return View(deliveryman);
        }

        //
        // GET: /Deliveryman/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Deliveryman/Create

        [HttpPost]
        public ActionResult Create(Deliveryman deliveryman)
        {
            if (ModelState.IsValid)
            {
                db.Deliverymen.Add(deliveryman);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(deliveryman);
        }

        //
        // GET: /Deliveryman/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Deliveryman deliveryman = db.Deliverymen.Find(id);
            if (deliveryman == null)
            {
                return HttpNotFound();
            }
            return View(deliveryman);
        }

        //
        // POST: /Deliveryman/Edit/5

        [HttpPost]
        public ActionResult Edit(Deliveryman deliveryman)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deliveryman).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(deliveryman);
        }

        //
        // GET: /Deliveryman/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Deliveryman deliveryman = db.Deliverymen.Find(id);
            if (deliveryman == null)
            {
                return HttpNotFound();
            }
            return View(deliveryman);
        }

        //
        // POST: /Deliveryman/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Deliveryman deliveryman = db.Deliverymen.Find(id);
            db.Deliverymen.Remove(deliveryman);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

mcv_app1/mcv_app1/Controllers/MetrostationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mcv_app1.Models;

namespace mcv_app1.Controllers
{
    public class MetrostationsController : Controller
    {
        private OrderDB db = new OrderDB();

        //
        // GET: /Metrostations/

        public ActionResult Index()
        {
            return View(db.Metrostations.ToList());
        }

        //
        // GET: /Metrostations/Details/5

        public ActionResult Details(int id = 0)
        {
            Metrostation metrostation = db.Metrostations.Find(id);
            if (metrostation == null)
            {
                return HttpNotFound();
            }
            return View(metrostation);
        }

        //
        // GET: /Metrostations/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Metrostations/Create

        [HttpPost]
        public ActionResult Create(Metrostation metrostation)
        {
            if (ModelState.IsValid)
            {
                db.Metrostations.Add(metrostation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(metrostation);
        }

        //
        // GET: /Metrostations/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Metrostation metrostation = db.Metrostations.Find(id);
            if (metrostation == null)
            {
                return HttpNotFound();
            }
            return View(metrostation);
        }

        //
        // POST: /Metrostations/Edit/5

        [HttpPost]
        public ActionResult Edit(Metrostation metrostation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(metrostation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(metrostation);
        }

        //
        // GET: /Metrostations/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Metrostation metrostation = db.Metrostations.Find(id);
            if (metrostation == null)
            {
                return HttpNotFound();
            }
            return View(metrostation);
        }

        //
        // POST: /Metrostations/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Metrostation metrostation = db.Metrostations.Find(id);
            db.Metrostations.Remove(metrostation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

mcv_app1/mcv_app1/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mcv_app1.Models;

namespace mcv_app1.Controllers
{
    public class OrderController : Controller
    {
        private OrderDB db = new OrderDB();

        //
        // GET: /Order/

        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Deliverymen).Include(o => o.Metrostations);
            return View(orders.ToList());
        }

        //
        // GET: /Order/Details/5

        public ActionResult Details(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // GET: /Order/Create

        public ActionResult Create()
        {
            ViewBag.DeliverymanId = new SelectList(db.Deliverymen, "DeliverymanId", "FIO");
            ViewBag.MetrostationId = new SelectList(db.Metrostations, "MetrostationId", "Name");
            return View();
        }

        //
        // POST: /Order/Create

        [HttpPost]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DeliverymanId = new SelectList(db.Deliverymen, "DeliverymanId", "FIO", order.DeliverymanId);
            ViewBag.MetrostationId = new SelectList(db.Metrostations, "MetrostationId", "Name", order.MetrostationId);
            return View(order);
        }

        //
        // GET: /Order/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.DeliverymanId = new SelectList(db.Deliverymen, "DeliverymanId", "FIO", order.DeliverymanId);
            ViewBag.MetrostationId = new SelectList(db.Metrostations, "MetrostationId", "Name", order.MetrostationId);
            return View(order);
        }

        //
        // POST: /Order/Edit/5

        [HttpPost]
        public ActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DeliverymanId = new SelectList(db.Deliverymen, "DeliverymanId", "FIO", order.DeliverymanId);
            ViewBag.MetrostationId = new SelectList(db.Metrostations, "MetrostationId", "Name", order.MetrostationId);
            return View(order);
        }

        //
        // GET: /Order/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // POST: /Order/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

mcv_app1/mcv_app1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/themes/base/css", "~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Заказы", "Index", "Order")</li>
                            <li>@Html.ActionLink("Исполнители", "Index", "Deliveryman")</li>
                            <li>@Html.ActionLink("Ст. метро", "Index", "Metrostations")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>